@startuml Interpreter classes

class BasicInterpreter {
    - env: BasicEnv
    - next_line: int = 0
    - runs: int = 0
    - semanticErrs: int = 0
    - runtimeErrs : int = 0
    - lines: std::map<int, std::unique_ptr<BasicStatement>>
    - console: BasicConsole
    + BasicInterpreter(console: BasicConsole): BasicInterpreter
    + emit(s: std::string): void
    - run(): int
    - lex(s: std::string): std::optional<std::list<BasicToken>>
    - parse(tokens: std::list<BasicToken>&): std::unique_ptr<BasicStatement>
    + semanticCheck(): bool
    + getStatementAt(addr: int): std::pair<int, std::optional<BasicStatement*>> {-1 if EOF, else positive number and statement}
}

abstract class BasicConsole {
    + {abstract} nextLine(): std::string*
    + {abstract} printLine(s: const std::string&): void
}

class BasicTerminal extends BasicConsole {
    + nextLine(): std::string*
    + printLine(s: const std::string&): void
}

class BasicFileConsole extends BasicConsole {
    + nextLine(): std::string*
    + printLine(s: const std::string&): void
}

class BasicEnv {
    - env: int[26]
    - callStack: std::list<int>
    + get(v: int): int {'A' <= v <= 'Z'}
    + set(v: int, val: int): void {'A' <= v <= 'Z'}
    + pushCurrLine(line: int): void
    + popReturnAddress(): int {returns -1 on error, else positive number}
}

BasicInterpreter o-- BasicConsole
BasicInterpreter o-- BasicStatement
BasicInterpreter o-- BasicEnv

BasicInterpreter -- BasicLexer : calls lexer >
BasicInterpreter -- BasicParser : calls parser >
BasicInterpreter -- BasicExecutor : calls executor >

@enduml
